import React from 'react';
import ChartRenderer from './ChartRenderer';
import { XMarkIcon, BeakerIcon } from '@heroicons/react/24/outline';

const DashboardCanvas = ({ data, onClose }) => {
    if (!data) return (
        <div className="w-full h-full flex flex-col items-center justify-center text-neutral-400 bg-neutral-50 dark:bg-neutral-900/50">
            <BeakerIcon className="w-12 h-12 mb-4 opacity-20" />
            <p className="text-sm font-bold uppercase tracking-widest opacity-50">Generative Canvas</p>
        </div>
    );

    return (
        <div className="w-full h-full p-8 bg-neutral-50 dark:bg-neutral-900 overflow-y-auto" style={{ animation: 'slideInRight 0.3s cubic-bezier(0.22,1,0.36,1)' }}>
            <div className="flex items-center justify-between mb-8 pb-4 border-b border-neutral-200 dark:border-neutral-800">
                <div>
                    <h1 className="text-2xl font-black text-neutral-900 dark:text-white">{data.title || "AI Analysis Dashboard"}</h1>
                    <p className="text-xs font-bold text-neutral-500 uppercase tracking-widest mt-1">Generated by RankPilot Intelligence</p>
                </div>
                <button onClick={onClose} className="p-2 bg-white dark:bg-neutral-800 border border-neutral-200 dark:border-neutral-700 rounded-xl text-neutral-500 hover:text-neutral-900 dark:hover:text-white transition-all shadow-sm">
                    <XMarkIcon className="w-5 h-5" />
                </button>
            </div>
            
            {/* Render metrics if present */}
            {data.metrics && data.metrics.length > 0 && (
                <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-4 mb-8">
                    {data.metrics.map((m, i) => (
                        <div key={i} className="p-5 bg-white dark:bg-neutral-800 border border-neutral-200 dark:border-neutral-700 rounded-3xl shadow-sm hover:shadow-md transition-shadow">
                            <p className="text-[10px] font-black text-neutral-500 uppercase tracking-widest mb-1">{m.label}</p>
                            <p className="text-2xl font-black text-neutral-900 dark:text-white">{m.value}</p>
                            {m.trend && (
                                <span className={`text-xs font-bold mt-2 block ${m.trend > 0 ? 'text-green-500' : 'text-red-500'}`}>
                                    {m.trend > 0 ? '+' : ''}{m.trend}%
                                </span>
                            )}
                        </div>
                    ))}
                </div>
            )}

            {/* Render primary chart from data */}
            <div className="bg-white dark:bg-neutral-800 border border-neutral-200 dark:border-neutral-700 rounded-3xl p-6 shadow-md">
                 <ChartRenderer type={data.chartType || 'line'} data={data} />
            </div>

            <style>{`
                @keyframes slideInRight {
                    from { opacity: 0; transform: translateX(50px); }
                    to { opacity: 1; transform: translateX(0); }
                }
            `}</style>
        </div>
    );
};

export default DashboardCanvas;
